---
# This role will back up all components of Elasticsearch and Confluent that are defined. 

# ===== Prep Tasks ===== #
# Proper Date Time Group (DTG): 'date -u +%d%H%MZ%b%y'
- name: Build time stamp
  ansible.builtin.set_fact:
    backup_timestamp: "{{ lookup('ansible.builtin.pipe', 'date -u +%Y%b%d') | upper }}"
  delegate_to: localhost
  run_once: true

- name: Where the backup directories are located
  ansible.builtin.set_fact:
    backup_location_elastic: /path/to/backup/elastic/backup_{{ backup_timestamp }}/{{ inventory_hostname }}/
    backup_location_confluent: /path/to/backup/confluent/backup_{{ backup_timestamp }}/{{ inventory_hostname }}/

- name: Backup Elastic
  ansible.builtin.include_tasks: backup_elastic.yml
  tags: 
    - backup_elastic

#- name: Backup Confluent
#  ansible.builtin.include_tasks: backup_confluent.yml
#  tags:
#    - backup_confluent

