---
- name: Update Logstash pipelines file
  hosts: localhost
  gather_facts: false
  vars:
    pipelines_file: /home/test/Desktop/ansible/pipelines.yml

  tasks:
    - name: Insert "# APPLE #" before first pipeline
      ansible.builtin.shell: |
        awk '
          BEGIN { inserted = 0 }
          {
            if (!inserted && $1 == "-" && $2 == "pipeline.id:") {
              print "# APPLE #"
              inserted = 1
            }
            print
          }
        ' "{{ pipelines_file }}" > /tmp/pipelines.new && mv /tmp/pipelines.new "{{ pipelines_file }}"
      args:
        executable: /bin/bash

    - name: Append PEAR pipeline block at end of file
      ansible.builtin.blockinfile:
        path: "{{ pipelines_file }}"
        marker: "# {mark} PEAR #"
        block: |
          - pipeline.id: pear-pipeline
            path.config: /etc/logstash/conf.d/pear-pipeline/*.conf
        insertafter: EOF

    - name: Insert blank line before PEAR block marker
      ansible.builtin.replace:
        path: "{{ pipelines_file }}"
        regexp: '(^# BEGIN PEAR #)'
        replace: '\n\1'

    - name: Output file contents
      ansible.builtin.command: cat "{{ pipelines_file }}"
      register: outputPL

    - name: Display modified pipeline file
      ansible.builtin.debug:
        var: outputPL.stdout_lines
