all:
  vars:
    # Cluster name for Elasticsearch
    clusterName: "aaron-dev"
    # Optional environment variable
    esEnvironment: "aaron-dev"
    ansible_ssh_user: "test"
    #ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  hosts:
    ubuntu001.elastic.pve:
      ansible_host: 192.168.30.11
    ubuntu002.elastic.pve:
      ansible_host: 192.168.30.12
    ubuntu003.elastic.pve:
      ansible_host: 192.168.30.13
    ubuntu004.elastic.pve:
      ansible_host: 192.168.30.14
    ubuntu005.elastic.pve:
      ansible_host: 192.168.30.15


elasticsearch:
  vars: 
    pathData: "/data"
  hosts:
    ubuntu001:
    ubuntu002:
    ubuntu003:
    ubuntu004:

kibana:
  hosts:
    ubuntu005:

logstash:
  hosts:
    ubuntu005:

haproxy:
  hosts:
    ubuntu005:

fleet_server:
  hosts:
    ubuntu005:
