---
- name: Install prerequisite packages
  ansible.builtin.apt:
    name: "{{ item }}"
    state: present
  loop:
    - gpg
    - apt-transport-https
    - nfs-kernel-server
  become: true

# ===== Open Internet ===== #
# Download packages to localhost, to reduce network load on WAN.
# LAN is faster anyways
- name: Open Internet ES Install
  when: deploymentType == openInternet
  block:
    - name: Download ES Binary
      ansible.builtin.get_url:
        url: https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-{{ esVersion }}-{{ platform }}
        dest: packages/
      delegate_to: localhost

    - name: Copy ES binary to hosts
      ansible.builtin.copy: 
        src: packages/elasticsearch-{{ esVersion }}-{{ platform }}
        dest: /etc/elasticsearch/
        owner: elasticsearch
        group: root
        mode: '0770'

    - name: Download Elasticsearch GPG key
      ansible.builtin.get_url:
        url: https://artifacts.elastic.co/GPG-KEY-elasticsearch
        dest: /tmp/GPG-KEY-elasticsearch
        mode: '0644'
      delegate_to: localhost
      when: pgpKey == yes

# ===== Air Gap ===== #
- name: Air Gap ES Install
  when: deploymentType == airGap
  block:
    - name: Copy ES binary to hosts
      ansible.builtin.copy: 
        src: packages/elasticsearch-{{ esVersion }}-{{ platform }}
        dest: /etc/elasticsearch/
        owner: elasticsearch
        group: root
        mode: '0770'

# ===== GPG Key ===== #
- name: Install PGP Key
  when: pgpKey == yes
  block:
    - name: Create /usr/share/keyrings if it doesn't exist
      ansible.builtin.file:
        path: /usr/share/keyrings
        state: directory
        mode: '0755'
        
    - name: Copy the GPG key to remote hosts
      ansible.builtin.copy:
        src: packages/GPG-KEY-elasticsearch
        dest: /etc/elasticsearch/
        owner: elasticsearch
        group: root
        mode: '0664'
      become: true
    - name: Convert GPG key to keyring format
      ansible.builtin.command: gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg /etc/elasticsearch/GPG-KEY-elasticsearch
      args:
        creates: /usr/share/keyrings/elasticsearch-keyring.gpg
      become: true

- name: Install Elasticsearch
  ansible.builtin.apt:
    deb: /etc/elasticsearch/elasticsearch={{ esVersion }}-{{ platform }}
  become: true
  notify: Restart Elasticsearch
  register: esPackage
