---
- name: Write /etc/NetworkManager/dispatch.d/ifup-local script
  ansible.builtin.copy:
    dest: /etc/NetworkManager/dispatch.d/ifup-local
    content: |
      if [ "$1" == "{{ NIC_Name }}" ]; then
        /sbin/ethtool -G eno6 rx 4096 tx 2048
      fi
    owner: root
    group: root
    mode: '0755'

- name: Restore SELinux context on ifup-local
  ansible.builtin.command: restorecon -v /etc/NetworkManager/dispatch.d/ifup-local
  when: ansible_selinux.status == "enabled"

