---- name: Update .vimrc on remote hosts with custom colors
  hosts: all
  become: yes
  gather_facts: false
  
  tasks:
      - name: Root -- Ensure only the required content is in .vimrc
        ansible.builtin.copy:
          dest: ~/.vimrc
          content: |
            colorscheme desert
            

      - name: msiemauto -- Ensure only the required content is in .vimrc
        ansible.builtin.copy:
          dest: /home/msiemauto/.vimrc
          content: |
            colorscheme desert
