---

- name: Prepare Hosts
  hosts: all
  roles:
    - prepare_hosts
  tags:
    - prepare_hosts
    - never
  gather_facts: false
  vars_files:
    - ~/.ansible/vaults/secrets.yml

- name: Install HAProxy
  hosts: haproxy
  roles:
    - haproxy
  tags:
    - haproxy
  gather_facts: true
  vars_files:
    - ~/.ansible/vaults/secrets.yml

- name: Install Elasticsearch
  hosts: elasticsearch
  roles:
    - elasticsearch-install
  tags:
    - elasticsearch
  gather_facts: false
  vars_files:
    - ~/.ansible/vaults/secrets.yml