---
  # ===== AIRGAP ===== #
- name: Debian Install
  when: ansible_distribution == 'Ubuntu' and deploymentType == "DODIN"
  block:
    - name: Install prerequisite packages (Debian)
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - gpg
        - apt-transport-https
        - nfs-kernel-server
      become: true

    - name: Add Elasticsearch GPG (Debian)
      ansible.builtin.shell:
        cmd: "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg"
        creates: /usr/share/keyrings/elasticsearch-keyring.gpg
      become: true

    - name: Add Elasticsearch Repo (Debian)
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        filename: "/etc/apt/sources.list.d/elastic-8.x"
        state: present
      become: true

    - name: Install Elasticsearch
      ansible.builtin.apt:
        name: elasticsearch-{{ esVersion }}
        state: present
      become: true
      notify: Restart Elasticsearch
      register: esPackage

    - name: Allow firewall ports (Ubuntu)
      when: ansible_distribution == 'Ubuntu'
      ansible.builtin.shell: ufw allow {{ item }}
      loop:
        - 5601/tcp
        - 9200/tcp
        - 8220/tcp
      become: true
      changed_when: false
      ignore_errors: true


  # ===== Open-internet ===== #
- name: Debian Install
  when: ansible_distribution == 'Ubuntu' and deploymentType == "DODIN"
  block:
    - name: Install prerequisite packages (Debian)
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - gpg
        - apt-transport-https
        - nfs-kernel-server
      become: true

    - name: Add Elasticsearch GPG (Debian)
      ansible.builtin.shell:
        cmd: "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg"
        creates: /usr/share/keyrings/elasticsearch-keyring.gpg
      become: true

    - name: Add Elasticsearch Repo (Debian)
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        filename: "/etc/apt/sources.list.d/elastic-8.x"
        state: present
      become: true

    - name: Install Elasticsearch
      ansible.builtin.apt:
        name: elasticsearch-{{ esVersion }}
        state: present
      become: true
      notify: Restart Elasticsearch
      register: esPackage

    - name: Allow firewall ports (Ubuntu)
      ansible.builtin.shell: ufw allow {{ item }}
      loop:
        - 5601/tcp
        - 9200/tcp
        - 8220/tcp
      become: true
      changed_when: false
      ignore_errors: true


  # ===== DODIN ===== # NEED TO DO
- name: Debian Install
  when: ansible_distribution == 'Ubuntu' and deploymentType == "DODIN"
  block:
    - name: Install prerequisite packages (Debian)
      ansible.builtin.package:
        name: "{{ item }}"
        state: present
      loop:
        - gpg
        - apt-transport-https
        - nfs-kernel-server
      become: true

    - name: Add Elasticsearch GPG (Debian)
      ansible.builtin.shell:
        cmd: "wget -qO - https://artifacts.elastic.co/GPG-KEY-elasticsearch | gpg --dearmor -o /usr/share/keyrings/elasticsearch-keyring.gpg"
        creates: /usr/share/keyrings/elasticsearch-keyring.gpg
      become: true

    - name: Add Elasticsearch Repo (Debian)
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/elasticsearch-keyring.gpg] https://artifacts.elastic.co/packages/8.x/apt stable main"
        filename: "/etc/apt/sources.list.d/elastic-8.x"
        state: present
      become: true

    - name: Install Elasticsearch
      ansible.builtin.apt:
        name: elasticsearch-{{ esVersion }}
        state: present
      become: true
      notify: Restart Elasticsearch
      register: esPackage

    - name: Allow firewall ports (Ubuntu)
      ansible.builtin.shell: ufw allow {{ item }}
      loop:
        - 5601/tcp
        - 9200/tcp
        - 8220/tcp
      become: true
      changed_when: false
      ignore_errors: true
