---
# =============================================================================
# inventory/group_vars/logstash/main.yml
# =============================================================================

pve_create_prefix:  24
pve_create_gateway: "192.168.30.1"
pve_bridge:         "vmbr1"
pve_vlan:           "30"

pve_clone_template_id:   9000
pve_clone_template_name: "elastic-ubuntu-cloudinit"
pve_clone_storage:       "mydata"
pve_clone_format:        "qcow2"
pve_clone_full:          true
pve_clone_target_node:   "walnut"

pve_cores:   4
pve_sockets: 1
pve_memory:  6144
pve_cpu:     "host"

pve_disk_size: 100
pve_scsihw:    "virtio-scsi-single"

pve_create_use_cloudinit: true
pve_ciuser: "ansible"

pve_tags:       "logstash,elasticsearch,production"
pve_onboot:     true
pve_protection: false
pve_agent:      "enabled=1"
pve_autostart:  true
