- name: Ensure nftables base table exists
  become: true
  ansible.builtin.shell: |
    nft list table inet filter || nft add table inet filter
  changed_when: false
  ignore_errors: true

- name: Ensure nftables input chain exists
  become: true
  ansible.builtin.shell: |
    nft list chain inet filter input || nft add chain inet filter input { type filter hook input priority 0 \; policy drop \; }
  changed_when: false
  ignore_errors: true

- name: Allow firewall ports (Debian with nftables)
  when: ansible_distribution == 'Debian'
  ansible.builtin.shell: |
    nft list chain inet filter input | grep -q 'tcp dport {{ item }}' || nft add rule inet filter input tcp dport {{ item }} ct state new accept
  loop:
  - 5601
  - 9200
  - 8220
  become: true
  changed_when: false
  ignore_errors: true

- name: Allow firewall ports (Ubuntu)
  when: ansible_distribution == 'Ubuntu'
  ansible.builtin.shell: ufw allow {{ item }}
  loop:
    - 5601/tcp
    - 9200/tcp
    - 8220/tcp
  become: true
  changed_when: false
  ignore_errors: true