---
# ================== READ ME ================== #

# ================== READ ME ================== #

- name: Install software on Ubuntu
  hosts: all
  order: sorted
  become: true
  gather_facts: true

  tasks:
    - name: Ensure required packages are installed
      ansible.builtin.apt:
        name:
          - ca-certificates
          - curl
          - vim
          - tree
          - net-tools
          - tcpdump
          - zypper
        state: present
        update_cache: true

    - name: Upgrade Ubuntu systems
      ansible.builtin.apt:
        upgrade: dist
        